spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306/api-usuario}?createDatabaseIfNotExist=true
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root123}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

#logging:
#  level:
#    org.springframework: DEBUG
#    org.hibernate: DEBUG
#    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
